export const queryKeys = {
  overview: ["overview"] as const,
  challenges: ["challenges"] as const,
  users: ["users"] as const,
  user: (id: string) => [...queryKeys.users, id] as const,
  currentUser: ["currentUser"] as const,
  rewards: ["rewards"] as const,
  reward: (id: string) => [...queryKeys.rewards, id] as const,
  settings: ["settings"] as const,
  badges: ["badges"] as const,
  dashboard: ["dashboard"] as const,
  profile: ["profile"] as const,
  quizProgress: ["quiz_progress"] as const,
  latestQuizResult: ["latest_quiz_result"] as const,
  saasMetrics: ["saas-metrics"] as const,
  adminSubscribers: ["admin-subscribers"] as const,
};
